- dockerfiles/br.Dockerfile
- dockerfiles/dm.Dockerfile
- dockerfiles/dumpling.Dockerfile
- dockerfiles/ng-monitoring.Dockerfile
- dockerfiles/pd.Dockerfile
- dockerfiles/ticdc.Dockerfile
- dockerfiles/tidb-binlog.Dockerfile
- dockerfiles/tidb-enterprise.Dockerfile
- dockerfiles/tidb-lightning-debug.Dockerfile
- dockerfiles/tidb-lightning.Dockerfile
- dockerfiles/tidb.Dockerfile
- dockerfiles/tiflash.Dockerfile
- dockerfiles/tikv.Dockerfile
> feat: add product dockerfiles

- dockerfiles/tikv.Dockerfile
support tikv mem profiling
add an environment variable
> feat: add tikv profiling env var

- dockerfiles/bases/Makefile
- dockerfiles/bases/pd-base/v1.1.0.Dockerfile
- dockerfiles/bases/pingcap-base/v1.1.0.Dockerfile
- dockerfiles/bases/tidb-base/v1.1.0.Dockerfile
- dockerfiles/bases/tikv-base/v1.1.0.Dockerfile
- dockerfiles/bases/tools-base/v1.1.0.Dockerfile
> feat: add base image dockerfile

- dockerfiles/bases/Makefile
- dockerfiles/bases/pd-base/Dockerfile
- dockerfiles/bases/pd-base/v1.1.0.Dockerfile
- dockerfiles/bases/pingcap-base/Dockerfile
- dockerfiles/bases/pingcap-base/v1.2.0.Dockerfile
- dockerfiles/bases/tidb-base/Dockerfile
- dockerfiles/bases/tidb-base/v1.1.0.Dockerfile
- dockerfiles/bases/tikv-base/Dockerfile
- dockerfiles/bases/tikv-base/v1.1.0.Dockerfile
- dockerfiles/bases/tools-base/Dockerfile
- dockerfiles/bases/tools-base/v1.1.0.Dockerfile
> chore: remove version from filename

- dockerfiles/bases/tidb-base/Dockerfile
> fix: install curl after rocky has curl-minial

- .vscode/settings.json
- Justfile
- dockerfiles-multi-stages/README.md
- dockerfiles-multi-stages/dm/Dockerfile
- dockerfiles-multi-stages/pd/Dockerfile
- dockerfiles-multi-stages/ticdc/Dockerfile
- dockerfiles-multi-stages/tidb/Dockerfile
- dockerfiles-multi-stages/tiflash/Dockerfile
- dockerfiles-multi-stages/tikv/Dockerfile
> feat: init multi stages building

- dockerfiles/br.Dockerfile
- dockerfiles/dm.Dockerfile
- dockerfiles/dumpling.Dockerfile
- dockerfiles/ng-monitoring.Dockerfile
- dockerfiles/pd.Dockerfile
- dockerfiles/ticdc.Dockerfile
- dockerfiles/tidb-binlog.Dockerfile
- dockerfiles/tidb-enterprise.Dockerfile
- dockerfiles/tidb-lightning-debug.Dockerfile
- dockerfiles/tidb-lightning.Dockerfile
- dockerfiles/tidb.Dockerfile
- dockerfiles/tiflash.Dockerfile
- dockerfiles/tikv.Dockerfile
> feat: upgrade base image

- OWNERS
- README.md
> feat: add system requirement

- dockerfiles/tidb-tools.Dockerfile
- tidb-tools image has not updated for years
- just the same structure as old
> feat: add tidb-tools image

- dockerfiles/bases/pingcap-base/Dockerfile
some dev want ps/ip command to debug, these package would inc size from 62MiB to 65MiB, seems acceptable
> feat: add ps/ip debug command to pingcap-base

- dockerfiles/WIP_ci_apps/ats/Dockerfile
- dockerfiles/WIP_ci_runtimes/bazel/Dockerfile
- ci runtime image: bazel
- ci app image: ats
> feat(dockerfiles): add ci job runtimes and apps images

- dockerfiles/WIP_ci_runtimes/bazel/Dockerfile
> fix(dockerfiles/WIP_ci_runtimes/bazel): fix issue `no build stage`

- dockerfiles/br.Dockerfile
- dockerfiles/dm.Dockerfile
- dockerfiles/dumpling.Dockerfile
- dockerfiles/ng-monitoring.Dockerfile
- dockerfiles/pd.Dockerfile
- dockerfiles/ticdc.Dockerfile
- dockerfiles/tidb-binlog.Dockerfile
- dockerfiles/tidb-enterprise.Dockerfile
- dockerfiles/tidb-lightning-debug.Dockerfile
- dockerfiles/tidb-lightning.Dockerfile
- dockerfiles/tidb-tools.Dockerfile
- dockerfiles/tidb.Dockerfile
- dockerfiles/tiflash.Dockerfile
- dockerfiles/tikv.Dockerfile
- fixed some security package in PR: https://github.com/PingCAP-QE/artifacts/pull/34
> fix(security): upgrade base image

- dockerfiles/WIP_ci_runtimes/bazel/Dockerfile
> fix(dockerfiles/WIP_ci_runtimes/bazel): fix base image tag from build args

- dockerfiles/ci-runtimes/base/Dockerfile
> fix(dockerfiles/ci-runtimes/base): fix install steps

- dockerfiles/ci-runtimes/base/Dockerfile
- dockerfiles/ci-runtimes/release.yaml
> feat(dockerfiles/ci-runtimes): update ci base image

- dockerfiles/ci-runtimes/base/Dockerfile
> feat(dockerfiles/ci-runtimes/base): Add java toolchain image

- dockerfiles/bases/pd-base/Dockerfile
- dockerfiles/bases/pingcap-base/Dockerfile
- dockerfiles/bases/tidb-base/Dockerfile
- dockerfiles/bases/tiflash-base/Dockerfile
- dockerfiles/bases/tikv-base/Dockerfile
- dockerfiles/bases/tools-base/Dockerfile
- dockerfiles/br.Dockerfile
- dockerfiles/dm.Dockerfile
- dockerfiles/dumpling.Dockerfile
- dockerfiles/ng-monitoring.Dockerfile
- dockerfiles/pd.Dockerfile
- dockerfiles/ticdc.Dockerfile
- dockerfiles/tidb-binlog.Dockerfile
- dockerfiles/tidb-enterprise.Dockerfile
- dockerfiles/tidb-lightning-debug.Dockerfile
- dockerfiles/tidb-lightning.Dockerfile
- dockerfiles/tidb-tools.Dockerfile
- dockerfiles/tidb.Dockerfile
- dockerfiles/tiflash.Dockerfile
- dockerfiles/tikv.Dockerfile
> chore: update product images to newer base image

- dockerfiles-multi-stages/dm/Dockerfile
- dockerfiles-multi-stages/pd/Dockerfile
- dockerfiles-multi-stages/ticdc/Dockerfile
- dockerfiles-multi-stages/tidb/Dockerfile
> chore: update go version to 1.20

- dockerfiles/ci-runtimes/base/Dockerfile
> fix(dockerfiles/ci-runtimes/base): fix codecov binary fetching for arm64 image

- dockerfiles/ci-runtimes/base/Dockerfile
- dockerfiles/ci-runtimes/release-build-base/Dockerfile
- dockerfiles/ci-runtimes/release-build-base/tikv/Dockerfile
- dockerfiles/ci-runtimes/release.yaml
> fix(dockerfiles/ci-runtimes): add release-build-base image

- dockerfiles-multi-stages/pd/Dockerfile
- dockerfiles/bases/pd-base/Dockerfile
- dockerfiles/pd.Dockerfile
Why:
- according to the add component plan
> feat: add re-recover and jq to pd

- dockerfiles/old-bases/arm64/centos-stream.Dockerfile
> feat: migrate centos-stream from private docker repo

- dockerfiles/ci-runtimes/release-build-base/Dockerfile
- packages/offline-packages.yaml.tmpl
> chore(packages): update offline package config

- packages/offline-packages.yaml.tmpl
- packages/packages.yaml.tmpl
> chore(packages): update release configs

- dockerfiles/br.Dockerfile
- dockerfiles/dm.Dockerfile
- dockerfiles/dumpling.Dockerfile
- dockerfiles/ng-monitoring.Dockerfile
- dockerfiles/pd.Dockerfile
- dockerfiles/ticdc.Dockerfile
- dockerfiles/tidb-binlog.Dockerfile
- dockerfiles/tidb-enterprise.Dockerfile
- dockerfiles/tidb-lightning-debug.Dockerfile
- dockerfiles/tidb-lightning.Dockerfile
- dockerfiles/tidb-tools.Dockerfile
- dockerfiles/tidb.Dockerfile
- dockerfiles/tiflash.Dockerfile
- dockerfiles/tikv.Dockerfile
- fix base image security
refs: https://github.com/PingCAP-QE/artifacts/pull/78
> fix: base image security

- .github/renovate.json
- dockerfiles/bases/pingcap-base/Dockerfile
- dockerfiles/bases/skaffold.yaml
- dockerfiles/ci-runtimes/skaffold.yaml
- renovate.json
Supports profiles:
- local build with docker, default is cluster build with kaniko.
- go 1.19.x, 1.20.x, 1.21.x
- product base images
> ci(dockerfiles/ci-runtimes): fix skaffold config

- packages/offline-packages.yaml.tmpl
Why:
since v7.5
- remove tikv-importer, mydumper
> feat: remove mydumper and tikv-importer for v7.5

- .github/renovate.json
> Action Required: Fix Renovate Configuration

- .github/workflows/ci.yaml
- dockerfiles/bases/skaffold.yaml
- dockerfiles/ci-runtimes/skaffold.yaml
> Build base images automaticly

- .github/workflows/ci.yaml
> ci: fix skaffold version

- dockerfiles/ci/base/Dockerfile
- dockerfiles/ci/release-build-base/Dockerfile
> chore(dockerfiles): bump oras to v1.1.0

- .github/workflows/release.yaml
> ci: split release from ci.yaml

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
> ci: add concurrent limit

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- Justfile
- dockerfiles/ci/release-utils/Dockerfile
> feat(dockerfiles/ci): add bash tool to release utils image

- packages/offline-packages.yaml.tmpl
- packages/packages.yaml.tmpl
> chore: update etcd version

- .github/workflows/release.yaml
> ci: fix release github workflow

- dockerfiles/bases/pd-base/Dockerfile
> feat: add perl to pd base image

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
> ci: fix github ci and release flows

- Justfile
- dockerfiles/cd/tikv/pd/Dockerfile
- packages/packages.yaml.tmpl
> fix(packages): fix packages.yaml.tmpl

- packages/packages.yaml.tmpl
> feat(packages): update packages.yaml.tmpl

- packages/packages.yaml.tmpl
- packages/scripts/build-package-artifacts.sh.tmpl
> fix(packges): fix package names and push destinations

- dockerfiles/cd/skaffold.yaml
- dockerfiles/ci/skaffold.yaml
not use date as the part of image tag, it will cause bad build caching rate.
> fix(dockerfiles): fix skaffold.yaml

- packages/packages.yaml.tmpl
- packages/scripts/build-package-images.sh.tmpl
currently the dockerfile in the repo limit build target platform to linux/amd64.
Ref:
- PingCAP-QE/ci#2628
> feat(packages): add dvanced-statefulset to packages configuration

- packages/packages.yaml.tmpl
> chore(packages): add arm64 image targets for `pingcap/advance-statefulset`

- packages/offline-packages.yaml.tmpl
- packages/packages.yaml.tmpl
Ref: https://docs.gomplate.ca/functions/semver/
It's contributed by us.
> fix(packages): use the latest gommplate function

- packages/scripts/build-package-artifacts.sh.tmpl
- packages/scripts/build-package-images.sh.tmpl
Changes:
- add output files for pushing results.
- make image build script can be called with flag arguments.
> feat(packages/scripts): output push results to files

- packages/scripts/build-package-artifacts.sh.tmpl
- fix argument parsing.
- fix var using.
> fix(pacakges): fix script template

- packages/scripts/build-package-images.sh.tmpl
> fix(pacakges): fix script template for building images

- packages/scripts/build-package-artifacts.sh.tmpl
> fix(packages/scripts): push more tags for OCI artifacts

- packages/packages.yaml.tmpl
- packages/scripts/build-package-artifacts.sh.tmpl
> fix(packages): make tag ok for feature branches or ther tree style branches

- packages/offline-packages.yaml.tmpl
- packages/packages.yaml.tmpl
- packages/scripts/build-offline-package-with-config.sh
- packages/scripts/gen-package-artifacts-with-config.sh
- packages/scripts/gen-package-images-with-config.sh
> opt(packages): simple package configurations

- packages/packages.yaml.tmpl
- packages/scripts/build-package-images.sh.tmpl
- packages/scripts/gen-package-images-with-config.sh
- packages/scripts/get-package-builder-with-config.sh
> feat(packages): support `builder` amd `build-args` options

- dockerfiles/cd/builders/skaffold.yaml
- dockerfiles/cd/builders/tidb-dashboard/Dockerfile
- dockerfiles/cd/builders/tiflash/Dockerfile
> fix(dockerfiles/cd/builders): fix multi stage dockerfile for tidb-dashboard

- packages/packages.yaml.tmpl
> fix(packages): add tarball artifacts for pd on fips profile for v6.5.x

- packages/packages.yaml.tmpl
> feat(dockerfiles/cd): add builder image for tidb-dashboard

- dockerfiles/cd/builders/ng-monitoring/Dockerfile
- dockerfiles/cd/builders/skaffold.yaml
- packages/packages.yaml.tmpl
> feat(dockerfiles/cd): add builder image for ng-monitoring

- .github/workflows/pull-verify-packages-config.yaml
- packages/packages.yaml.tmpl
- packages/scripts/build-package-artifacts.sh.tmpl
- packages/scripts/gen-package-artifacts-with-config.sh
- packages/scripts/gen-package-images-with-config.sh
> refactor(packages): increase readability of package.yaml.tmpl

- dockerfiles/products/tiproxy/Dockerfile
- packages/packages.yaml.tmpl
- packages/scripts/ci.sh
> feat(packges): add tiproxy into configuration

- packages/scripts/build-package-artifacts.sh.tmpl
> feat(packages/scripts): add checksum(sha256) for files in OCI

- packages/packages.yaml.tmpl
- packages/scripts/ci.sh
> feat: add monitoring image

- packages/packages.yaml.tmpl
> fix(pcakges): fix packages.yaml.tmpl for tiflow on v6.5.x versions

- packages/packages.yaml.tmpl
- packages/scripts/gen-package-artifacts-with-config.sh
- packages/scripts/gen-package-images-with-config.sh
- packages/scripts/gen-package-offline-package-with-config.sh
> fix(pcakges): fix packages.yaml.tmpl for tidb-operator on fips profile

- packages/offline-packages.yaml.tmpl
- packages/scripts/build-package-artifacts.sh.tmpl
- packages/scripts/build-package-images.sh.tmpl
- packages/scripts/gen-package-offline-package-with-config.sh
> fix(packages): fix configuration for offline packages

- packages/packages.yaml.tmpl
> fix(packages): fix builders for `tidb-tools`

- packages/packages.yaml.tmpl
> fix(packages): fix builder for tidb-tools

- packages/offline-packages.yaml.tmpl
> refactor(packages/scripts): perfer regex to linux glob wildmask

- packages/packages.yaml.tmpl
> feat: add tiflow-engine docker image

- packages/packages.yaml.tmpl
Reverts PingCAP-QE/artifacts#219
> Revert "feat: add tiflow-engine docker image"

- packages/delivery.yaml
> feat(packages): add image copy rules

- dockerfiles/cd/builders/skaffold.yaml
> chore(deps): add golang builders for 1.18.x

- packages/delivery.yaml
- trunk branch images
- release branch images
> feat(packages): add image delivery rules

- packages/delivery.yaml
> fix(packages): fix src image repo

- packages/packages.yaml.tmpl
it starts from v8.0.0
Fixes #203
> chore(pacakges): upgrade prometheus version to v2.49.1

- dockerfiles/cd/utils/release/Dockerfile
> fix(dockerfiles/cd/utils/release): add uuidgen tool

- .github/renovate.json
> ci(renovate): split the patch and minor updating

- packages/delivery-schema.json
> chore(pacakges): add json schema for delivery.yaml

- packages/packages.yaml.tmpl
> fix(pacakges): bump release util image to `v20231216-81-g3fc5aaa`

- packages/packages.yaml.tmpl
> fix(pacakges): delete git clone step in steps

- packages/packages.yaml.tmpl
> fix(pingcap/ng-monitoring): fix rule file paths

- packages/packages.yaml.tmpl
> fix(pingcap/ng-monitoring): update packages.yaml.tmpl

- packages/packages.yaml.tmpl
- packages/scripts/ci.sh
> fix(packages): add enterprise profiles

- packages/packages.yaml.tmpl
> fix(pingcap/monitoring): fix builders

- packages/README.md
- packages/packages.yaml.tmpl
- packages/scripts/ci.sh
> fix(packages): rename profile `debug` to `failpoint`

- packages/offline-packages.yaml.tmpl
- packages/packages.yaml.tmpl
> fix(packages): bump etcdctl to v3.4.30

- packages/packages.yaml.tmpl
Reverts PingCAP-QE/artifacts#266
> Revert "Update packages.yaml.tmpl"

- packages/packages.yaml.tmpl
> feat(packages): add tag for OCI artifacts with release version

- packages/offline-packages.yaml.tmpl
Why:
- we've add PCC and dba to all platform
> feat: add pcc and dba to all platform

- packages/scripts/build-package-artifacts.sh.tmpl
- packages/scripts/build-package-images.sh.tmpl
- packages/scripts/compose-offline-packages-artifacts.sh.tmpl
> feat(packages/scripts): add label for oci artifacts and iamges

- packages/scripts/build-package-images.sh.tmpl
> fix(packages/scripts): fix for digest collecting

- packages/scripts/build-package-artifacts.sh.tmpl
- packages/scripts/build-package-images.sh.tmpl
- packages/scripts/compose-offline-packages-artifacts.sh.tmpl
> fix(package/scripts): fix taging for artifacts

- packages/delivery.yaml
Why:
- fix typo from dbass to dbaas
> fix: typo dbaas

- packages/packages.yaml.tmpl
> fix(package): tidb-ctl only has master branch

- packages/packages.yaml.tmpl
- packages/scripts/build-package-artifacts.sh.tmpl
- packages/scripts/build-package-images.sh.tmpl
- packages/scripts/gen-package-artifacts-with-config.sh
- packages/scripts/gen-package-images-with-config.sh
- label for images
- config key for artifacts
> feat(package/scripts): add `net.pingcap.tibuild.git-sha` info

- packages/packages.yaml.tmpl
> fix(packages): fix tidb-binlog image context config

- packages/offline-packages.yaml.tmpl
- packages/scripts/compose-offline-packages-artifacts.sh.tmpl
- packages/scripts/gen-package-offline-package-with-config.sh
> feat(package): support enterprise tiup offline deploy packages

- packages/offline-packages.yaml.tmpl
- packages/scripts/compose-offline-packages-artifacts.sh.tmpl
- packages/scripts/pre-to-ga-tag.sh
> feat(packages/scripts): add pre to ga script

- packages/scripts/build-package-artifacts.sh.tmpl
- packages/scripts/build-package-images.sh.tmpl
- packages/scripts/compose-offline-packages-artifacts.sh.tmpl
> opt(packages): add retry for http fetching

- packages/offline-packages.yaml.tmpl
fix the republish tiup name for tiflash
> fix(packges): fix offline-package config

- packages/delivery.yaml
> feat(packages): add image copy rule for `advanced-statefulset`

- packages/offline-packages.yaml.tmpl
Reverts PingCAP-QE/artifacts#295
> Revert "fix(packges): hotfix offline-package config for v8.0.0"

- dockerfiles/cd/utils/release/Dockerfile
> feat(dockerfiles/cd): add tiup tool into release util image

- packages/offline-packages.yaml.tmpl
- packages/packages.yaml.tmpl
- packages/scripts/gen-package-artifacts-with-config.sh
- packages/scripts/gen-package-images-with-config.sh
- packages/scripts/gen-package-offline-package-with-config.sh
- packages/scripts/get-package-builder-with-config.sh
> feat(packages/scripts): support build with custom artifact registry

- packages/packages.yaml.tmpl
> fix(packages/scripts): fix builder for tiflash

- .github/workflows/pull-cd-builder-images.yaml
- .github/workflows/release-cd-builder-images.yaml
- dockerfiles/cd/builders/skaffold.yaml
- dockerfiles/cd/builders/tikv/Dockerfile
> feat(dockerfiles/cd/builders/tikv): support custom devtoolset version

- dockerfiles/bases/pingcap-base/Dockerfile
- dockerfiles/bases/skaffold.yaml
- dockerfiles/cd/builders/tikv/fips.Dockerfile
> feat(dockerfiles/bases): upgrade base image to rockylinux 9.4

- dockerfiles/ci/release-build-base/Dockerfile
update git version from 2.40.1 to 2.40.2 to fix security issue
> fix: update git version to fix security issue

- packages/delivery.yaml
> feat(packages): add image copy rule for tidb-operator

- packages/packages.yaml.tmpl
> fix(pingcap/tidb-operator): fix builder image for tidb-operator

- packages/packages.yaml.tmpl
add uuidgen tool in golang image
___
enhancement
___
- Updated the builder image for `tidb-operator` in the `packages/packages.yaml.tmpl` file.
- Changed the image from `golang:1.21.11` to `ghcr.io/pingcap-qe/cd/builders/tidb-operator:v20240325-52-ga8d3395`.
___
<tr>
<td>
<details>
<summary><strong>packages.yaml.tmpl</strong><dd><code>Update builder image for tidb-operator</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
packages/packages.yaml.tmpl
<li>Updated the builder image for …
> fix(pingcap/tidb-operator): fix builder image

- packages/packages.yaml.tmpl
prepare file `br` to build image tidb-ligntning of release-6.5
> fix(packages): update packages.yaml.tmpl

- dockerfiles/cd/builders/tikv/Dockerfile
> fix(dockerfiles/cd/builders/tikv): fix devtoolset missing issue

- .github/workflows/pull-cd-builder-images2.yaml
- Justfile
- dockerfiles/cd/builders/ng-monitoring/Dockerfile
- dockerfiles/cd/builders/pd/Dockerfile
- dockerfiles/cd/builders/tidb-dashboard/Dockerfile
- dockerfiles/cd/builders/tidb-operator/Dockerfile
- dockerfiles/cd/builders/tidb/Dockerfile
- dockerfiles/cd/builders/tiflash/Dockerfile
- dockerfiles/cd/builders/tiflow/Dockerfile
- dockerfiles/cd/builders/tikv/Dockerfile
> ci: add e2e test workflow for cd builder images

- .github/workflows/pull-cd-builder-images2.yaml
- Justfile
> ci: refactor msb build job to make it able to trigger by comment in PR.

- .github/workflows/pull-cd-builder-images2.yaml
- packages/packages.yaml.tmpl
> ci: fix workflow pull-cd-builder-images2.yaml

- packages/scripts/compose-offline-packages-artifacts.sh.tmpl
> fix(packages/scripts): fix compose-offline-packages-artifacts.sh.tmpl

- packages/scripts/gen-delivery-tiup-script.sh
> feat(packages/scripts): add force version support for tiup publish

- packages/delivery.yaml
- packages/offline-packages.yaml.tmpl
- packages/packages.yaml.tmpl
This reverts commit a73490d69259342bba3ef8ada5385b4f448faf53.
> Revert "chore: fixate patch version for binlog (#402)"

- packages/packages.yaml.tmpl
> fix(packages): fix artifacts config for pd component

- packages/packages.yaml.tmpl
> fix(packages): fix artifacts config for tiproxy component of experiment profile

- packages/packages.yaml.tmpl
> feat(packages): use go1.23 to build artifacts for experiment profile

- dockerfiles/products/tikv/le6.5/Dockerfile
Reverts PingCAP-QE/artifacts#426
> Revert "chore(deps): update ghcr.io/pingcap-qe/bases/tikv-base docker tag to v1.0.1"

- dockerfiles/bases/ng-monitoring-base/Dockerfile
- dockerfiles/bases/ng-monitoring-base/release-6.5.Dockerfile
- dockerfiles/bases/pd-base/Dockerfile
- dockerfiles/bases/pd-base/release-6.5.Dockerfile
- dockerfiles/bases/pingcap-base/Dockerfile
- dockerfiles/bases/skaffold.yaml
- dockerfiles/bases/tidb-base/Dockerfile
- dockerfiles/bases/tidb-base/release-6.5.Dockerfile
- dockerfiles/bases/tiflash-base/Dockerfile
- dockerfiles/bases/tikv-base/Dockerfile
- dockerfiles/bases/tikv-base/fips.Dockerfile
- dockerfiles/bases/tikv-base/release-6.5.Dockerfile
- dockerfiles/bases/tools-base/Dockerfile
- dockerfiles/bases/tools-base/release-6.5.Dockerfile
Reverts PingCAP-QE/artifacts#431
> Revert "fix(dockerfiles/bases): shrink base image size"

- packages/packages.yaml.tmpl
> fix(packages): update builder config with new images

- .github/workflows/pull-cd-builder-images-centos7.yaml
- .github/workflows/pull-cd-util-images.yaml
- .github/workflows/pull-ci-runtime-images.yaml
- .github/workflows/pull-prod-runtime-images.yaml
- .github/workflows/release-cd-builder-images-centos7.yaml
- .github/workflows/release-cd-util-images.yaml
- .github/workflows/release-ci-runtime-images.yaml
- .github/workflows/release-prod-runtime-images.yaml
- Justfile
- dockerfiles/bases/skaffold.yaml
- dockerfiles/cd/builders/skaffold-centos7.yaml
- dockerfiles/cd/builders/skaffold.yaml
- dockerfiles/cd/utils/skaffold.yaml
- dockerfiles/ci/skaffold.yaml
> ci: fix builder image tags and simpfy the skaffold config

- packages/packages.yaml.tmpl
> fix(packages): fix builder for tidb-operator

- dockerfiles/ci/jenkins/tiflash/Dockerfile
add clang-tools 17.0.6 in tiflash ci image
> feat: add clang-tools in tiflash ci image

- dockerfiles/ci/jenkins/tiflash/Dockerfile
This pull request modifies the `dockerfiles/ci/jenkins/tiflash/Dockerfile` to update the base image, change user configurations, and install additional packages. The most important changes include removing the creation of the `jenkins` user, adding new package installations, and updating environment variables.
* Removed the creation of the `jenkins` user and its addition to the sudoers file. (`dockerfiles/ci/jenkins/tiflash/Dockerfile`)
* Changed the `CARGO_HOME` environment variable to point to `/root/.cargo` instead of `/home/jenkins/.cargo`. (`dockerfiles/ci/jenkins/tiflash/Dockerfile`)
* Added installation of `xz`, `xz-libs`, and `glibc-langpack-en` packages. (`dockerfiles/ci/jenkins/tiflash/Dockerfile`)
* Added installation of MySQL client by downloading and installing the MySQL …
> feat: add missing xz tool in tiflash ci image

- packages/packages.yaml.tmpl
> fix(packages): update builder image tags

- dockerfiles/cd/builders/tiflash/Dockerfile
> fix(dockerfiles/cd/builders/tiflash): update llvm installation steps

- dockerfiles/products/tidb/~6.5.12/tidb.Dockerfile
> fix(dockerfiles/product/tidb): fix product docker file for patch version ~v6.5.12

- dockerfiles/ci/base/Dockerfile
- dockerfiles/ci/jenkins/tikv/Dockerfile
Add more tools to ci jenkins
* mysql 5.7
* percona-toolkit
Fix rust install package error
* cargo-platform v0.1.9 need rustc 1.78 or newer
> feat: ci image add mysql 5.7

- .github/workflows/pull-cd-builder-images-centos7.yaml
- .github/workflows/pull-cd-builder-images.yaml
- .github/workflows/release-cd-builder-images-centos7.yaml
- .github/workflows/release-cd-builder-images.yaml
- dockerfiles/cd/builders/ticdc/Dockerfile
- dockerfiles/cd/builders/ticdc/skaffold-centos7.yaml
- add gcc into rocky linux based builder image
- fix skaffold-centos7.yaml file
> fix(ticdc): fix builder image

- .github/workflows/pull-cd-builder-images-centos7.yaml
- .github/workflows/pull-cd-builder-images.yaml
- .github/workflows/release-cd-builder-images-centos7.yaml
- .github/workflows/release-cd-builder-images.yaml
avoid GitHub action job exit abnormal.
> fix(ci): add concurrency limit for matrix

- .github/workflows/pull-cd-builder-images-centos7.yaml
- .github/workflows/pull-cd-builder-images.yaml
- .github/workflows/release-cd-builder-images-centos7.yaml
- .github/workflows/release-cd-builder-images.yaml
> ci: limit run concurrency of cd builder image

- packages/delivery.yaml
- packages/scripts/gen-delivery-image-commands.ts
> fix(packages): fix image delivery

- packages/packages.yaml.tmpl
> chore(packages): update packages.yaml.tmpl for tikv

- packages/packages.yaml.tmpl
Update TiKV builder to v2024.10.8-139-g74d1fec with devtoolset8/9 variants and add build configuration for the new experiment profile using devtoolset9
> feat(packages): Add TiKV experiment profile and update builder images

- packages/packages.yaml.tmpl
> feat(packages): enable next-gen flag in Linux build script for tiflash

- .github/workflows/release-ci-runtime-images.yaml
Reverts PingCAP-QE/artifacts#648
> Revert "chore(workflow): Update CI workflow to use arc-runner-set-pingcap-qe for image publishing"

- dockerfiles/products/tici/Dockerfile
- packages/packages.yaml.tmpl
Replace tici binary with meta_service_server and worker_node_server.
> fix(tici): fix packaging config and dockerfile

- packages/packages.yaml.tmpl
> chore(tici): update builder image tag

- packages/packages.yaml.tmpl
> fix(tici): fix builder image

- dockerfiles/products/ng-monitoring/Dockerfile
- dockerfiles/products/pd/Dockerfile
- dockerfiles/products/ticdc/Dockerfile
- dockerfiles/products/tici/Dockerfile
- dockerfiles/products/tidb-dashboard/Dockerfile
- dockerfiles/products/tidb-tools/Dockerfile
- dockerfiles/products/tidb/br.Dockerfile
- dockerfiles/products/tidb/dumpling.Dockerfile
- dockerfiles/products/tidb/tidb-lightning.Dockerfile
- dockerfiles/products/tidb/tidb.Dockerfile
- dockerfiles/products/tidb/tidb.enterprise.Dockerfile
- dockerfiles/products/tiflash/Dockerfile
- dockerfiles/products/tiflow/dm.Dockerfile
- dockerfiles/products/tiflow/sync-diff-inspector.Dockerfile
- dockerfiles/products/tiflow/ticdc.Dockerfile
- dockerfiles/products/tikv/Dockerfile
- dockerfiles/products/tikv/fips.Dockerfile
- dockerfiles/products/tikv/next-gen.Dockerfile
- dockerfiles/products/tiproxy/Dockerfile
- Adds base, root, and nonroot stages to all product Dockerfiles.
- Default build is root; use --target nonroot for non-root images.
> feat(dockerfiles/products): add multi-stage Dockerfiles with root and non-root targets
