dockerfiles/bases/pd-base/Dockerfile, dockerfiles/bases/pingcap-base/Dockerfile, dockerfiles/bases/tidb-base/Dockerfile, dockerfiles/bases/tikv-base/Dockerfile, dockerfiles/bases/tools-base/Dockerfile
Why:
- rocky has no newer release yet
- fix CVE for these upgraded packages
=> fix(security): upgrade packages

dockerfiles/bases/Makefile, dockerfiles/bases/tidb-base/Dockerfile, dockerfiles/bases/tiflash-base/Dockerfile
Why:
- operator say they need wget when deploy across k8s cluster
=> feat: tidb/tiflash add wget according to operator

dockerfiles/bases/pingcap-base/Dockerfile
- update rocky to 9.2 to make it more security with fixes.
- upgrade busybox to 1.36.1 to include updates from upstream image.
- remove `dnf upgrade` since the the package is updated in rocky 9.2, no need it again.
- bump rocky image tag to 9.2 group
- bump busybox image tag to 1.36.1
- delete the no longer needed step: `dnf upgrade`.
- already pass security scanning by security team
=> fix(dockerfiles/bases/pingcap-base): bump the base images to make more security

dockerfiles/bases/Makefile, dockerfiles/bases/pd-base/Dockerfile, dockerfiles/bases/pingcap-base/Dockerfile, dockerfiles/bases/tidb-base/Dockerfile, dockerfiles/bases/tiflash-base/Dockerfile, dockerfiles/bases/tikv-base/Dockerfile, dockerfiles/bases/tools-base/Dockerfile
Why:
- fix base image security
- 
- better makefile for parallel build
=> fix: base image security

packages/offline-packages.yaml.tmpl
Why:
- remove spark and tispark since v7.5
=> chore: remove tispark and spark since v7.5

packages/packages.yaml.tmpl, packages/scripts/build-package-artifacts.sh.tmpl, packages/scripts/build-package-images.sh.tmpl
What changes for tiflow
===
1. add `darwin` as support target os.
2. add os conditional steps for tiflow darwin targets, we use nvm to provide different nodejs versions.
=> fix(packges): add mac build targets for tiflow

dockerfiles/bases/skaffold.yaml
=> chore: bump base image verison

dockerfiles/br.Dockerfile, dockerfiles/dm.Dockerfile, dockerfiles/dumpling.Dockerfile, dockerfiles/ng-monitoring.Dockerfile, dockerfiles/pd.Dockerfile, dockerfiles/products/br.Dockerfile, dockerfiles/products/dm.Dockerfile, dockerfiles/products/dumpling.Dockerfile, dockerfiles/products/ng-monitoring.Dockerfile, dockerfiles/products/pd.Dockerfile, dockerfiles/products/ticdc.Dockerfile, dockerfiles/products/tidb-binlog.Dockerfile, dockerfiles/products/tidb-enterprise.Dockerfile, dockerfiles/products/tidb-lightning-debug.Dockerfile, dockerfiles/products/tidb-lightning.Dockerfile, dockerfiles/products/tidb-tools.Dockerfile, dockerfiles/products/tidb.Dockerfile, dockerfiles/products/tiflash.Dockerfile, dockerfiles/products/tikv.Dockerfile, dockerfiles/ticdc.Dockerfile, dockerfiles/tidb-binlog.Dockerfile, dockerfiles/tidb-enterprise.Dockerfile, dockerfiles/tidb-lightning-debug.Dockerfile, dockerfiles/tidb-lightning.Dockerfile, dockerfiles/tidb-tools.Dockerfile, dockerfiles/tidb.Dockerfile, dockerfiles/tiflash.Dockerfile, dockerfiles/tikv.Dockerfile
- bump base image version to fix security problems
- zero security issues scanned by security team
=> chore: bump base image

.github/workflows/pull-verify-packages-config.yaml
=> ci: add job "Pull test for packages cfg"

.github/workflows/pull-cd-builder-images.yaml, .github/workflows/pull-verify-packages-config.yaml, .github/workflows/release-cd-builder-images.yaml, .github/workflows/release-cd-util-images.yaml, .github/workflows/release-ci-runtime-images.yaml, .github/workflows/release-prod-runtime-images.yaml, dockerfiles/cd/builders/skaffold.yaml, dockerfiles/cd/utils/skaffold.yaml, dockerfiles/ci/skaffold.yaml
=> ci: split skaffold module for tiflash builder image

packages/packages.yaml.tmpl
=> feat: add tiup tarball artifact for fips

.github/workflows/pull-verify-packages-config.yaml, dockerfiles/cd/builders/ng-monitoring/Dockerfile, dockerfiles/cd/builders/skaffold.yaml
=> ci: fix verify flow for packages config

.github/workflows/pull-verify-packages-config.yaml, packages/packages.yaml.tmpl
=> feat(packages): add builder  for ng-monitoring

.github/workflows/pull-verify-packages-config.yaml, packages/README.md, packages/offline-packages.yaml.tmpl, packages/packages.yaml.tmpl, packages/scripts/get-package-builder-with-config.sh
also add the the verify step for the README.md with shelldoc tool
Ref: https://github.com/endocode/shelldoc
=> docs(packages): Update README.md

packages/packages.yaml.tmpl, packages/scripts/build-package-artifacts.sh.tmpl, packages/scripts/gen-package-artifacts-with-config.sh
The delivery jobs can utilize the meta data to publish TiUP packages, etc...
=> feat(packages): add meta data into the OCI artifacts

packages/README.md, packages/packages.yaml.tmpl, packages/scripts/build-package-artifacts.sh.tmpl, packages/scripts/build-package-images.sh.tmpl, packages/scripts/ci.sh
- container images.
- add plugins tarballs.
- will not publish tiup for enterprise profile.
=> feat(packages): support enterprise build profile for tidb

packages/packages.yaml.tmpl
=> fix(packages): add tiup metadata for cdc

packages/offline-packages.yaml.tmpl, packages/packages.yaml.tmpl, packages/scripts/ci.sh
- `tidb-tools` support Mac targets, we add it here.
=> fix(packages): fix config for `tidb-binlog` and `tidb-tools`

.gitignore, packages/README.md, packages/packages.yaml.tmpl, packages/scripts/build-package-artifacts.sh.tmpl, packages/scripts/build-package-images.sh.tmpl, packages/scripts/ci.sh
=> feat: add prometheus build config

packages/packages.yaml.tmpl
Why:
- mac/darwin has different version
- the version is a param and changed during groovy run, which misleads former PR
=> fix: prometheus path

packages/packages.yaml.tmpl, packages/scripts/build-package-artifacts.sh.tmpl
=> feat: support grafana

packages/packages.yaml.tmpl
fix build grafana error:
```sh
empty branch/tag info for tidb
```
=> fix: add target branch env var

packages/packages.yaml.tmpl
=> feat: build grafana without pull

packages/packages.yaml.tmpl
- monitoring has no compiling steps, so simply use one builder
- need wget
=> feat: use simple golang builder for monitor

packages/packages.yaml.tmpl
- need wget for builder
- go 1.18 not available
=> chore: update ng-monitoring builder image

packages/scripts/build-package-artifacts.sh.tmpl, packages/scripts/build-package-images.sh.tmpl, packages/scripts/compose-offline-packages-artifacts.sh.tmpl
not pull all files, but just the needed file.
=> perf(packages/scripts): improve efficiently of fetching file from artifacts

packages/packages.yaml.tmpl
- download tiup-ctl from github rather than inner fileserver
- fix artifactory for `tidb-ctl`.
- fix artifactory for cdc.
- fix all upstream oci artifacts's tag and file path
=> fix(packages): some fix for file sources

packages/scripts/build-package-images.sh.tmpl
Avoid kaniko cache issue
Ref: https://github.com/GoogleContainerTools/kaniko/issues/1469
=> fix build-package-images.sh.tmpl

packages/scripts/build-package-images.sh.tmpl
Reverts PingCAP-QE/artifacts#224
=> Revert "fix build-package-images.sh.tmpl"

packages/packages.yaml.tmpl, packages/scripts/ci.sh
- update builder image
- no binary needed
=> fix: tiflow-operator builder

packages/packages.yaml.tmpl
It will not build the go plugins, and it's valid from v7.1.0.
=> feat(packages): add `enterprise-without-plugins` profile for tidb repo

packages/delivery.yaml, packages/scripts/gen-delivery-image-commands.ts, packages/scripts/gen-delivery-images-with-config.sh
central congfig to control image delivery:
1. the config yaml.
2. the script to generate the shell commands, make it able to debug local before deploy on CD flows.
=> feat(packages): add image copy scripts

packages/packages.yaml.tmpl
=> feat: add tidb-ctl config

dockerfiles/cd/builders/pd/Dockerfile, dockerfiles/cd/builders/skaffold.yaml, dockerfiles/ci/skaffold.yaml
=> feat(dockerfiles/cd/builders): add builder image with go 1.22.x

packages/packages.yaml.tmpl
It supports darwin arm64 buiding from v3.5.5 by etcd-io office source.
Ref: https://github.com/etcd-io/etcd/issues/14001
=> fix(pacakges): update the downloading url for etcd binary

packages/packages.yaml.tmpl, packages/scripts/ci.sh
As we have talked and decided internally:
1. most file is same as monitoring.
2. manager granfa and prometheus versions from `pingcap/monitoring` engineering.
3. ng-monitoring is a more standalone project, in future it will splited from "prometheus" tiup pkg.
=> refactor(pingcap/ng-monitoring,pingcap/monitoring): drive the "prometheus" tiup pkg building from `pingcap/monitoring`

packages/packages.yaml.tmpl
For example:
run: "./packages/scripts/gen-package-artifacts-with-config.sh monitoring darwin amd64 v7.1.1 release v8.0.0 ''"
output:
```bash
function build() {
export TARGET=release-8.0
export TARGET_OS=darwin TARGET_ARCH=amd64
make grafana_without_pull
make default -C ng-monitoring
make output/prometheus
echo "building finished."
}
```
=> feat(pingcap/monitoring): support build for tag creating triggers

packages/packages.yaml.tmpl
Must have artifacts when image building need pre-compiled binaries.
=> fix(pingcap/ng-monitoring): fix image building

packages/delivery.yaml, packages/scripts/gen-delivery-image-commands.ts
- for tidb/pd/tikv/tiflash: sync like:
`hub.pingcap.net/pingcap/tidb/images/tidb-server:v7.1.2-enterprise-pre -> hub.pingcap.net/qa/tidb-enterprise:v7.1.2-pre`
- for others: sync like:
`hub.pingcap.net/pingcap/tidb/images/br:v7.1.2-pre -> hub.pingcap.net/qa/br-enterprise:v7.1.2-pre`
#How:
- add tag_regex_replace to remove enterprise tag
=> feat: support sync enterprise image

packages/delivery.yaml
- sync RC enterprise image to GCR
-  `hub.pingcap.net/pingcap/tidb/images/tidb-server:v7.5.0-pre-enterprise` -> `hub.pingcap.net/qa/tidb-enterprise:v7.5.0-pre` -> `gcr.io/pingcap-public/dbaas/tidb:v7.5.0-pre`
=> feat: sync RC enterprise image to gcr

packages/delivery.yaml
Why:
- need sync failpoint image to QA project
=> fix: sync failpoint image to qa

packages/delivery.yaml, packages/scripts/pre-to-ga-tag.sh
why:
- improve maintainability and readability
Tested:
- ✅ diff with old and new with `yq --output-format json '.image_copy_rules ' packages/delivery.yaml`
=> opt(packages): abstract the delivery tag regexes

packages/offline-packages.yaml.tmpl
=> fix(packages): fix offline packages config

packages/offline-packages.yaml.tmpl, packages/packages.yaml.tmpl
Before this, I ideally thought that there was no difference in the file list contained in the tiup package in the tiup offline package, but only the difference in the program content of the two processes. But in fact, due to the lack of transparency and precision in many historical processes, there is a direct and undue difference between the enterprise version and the community version.
For continued consistency, the configuration is updated here to maintain the status quo. But here we use precise file names to control, rather than directories.
=> fix(packages): fix offline enterprise server package config

packages/scripts/gen-delivery-tiup-script.sh
usage:
./packages/scripts/gen-delivery-tiup-script.sh <oci-artifact-url> true|false <save-publish-script>
example:
./packages/scripts/gen-delivery-tiup-script.sh hub.pingcap.net/pingcap/tidb/package:v8.1.0-pre_darwin_amd64 false xxx.sh
=> feat(packages/scripts): add script `gen-delivery-tiup-script.sh`

packages/packages.yaml.tmpl
=> chore(deps): bump cd builder images

dockerfiles/ci/base/Dockerfile
* update git version from 2.39.2 to 2.39.4, fix git security vulnerabilities
=> fix: update git version to fix security issue

packages/packages.yaml.tmpl
tiflash use llvm17 to build on version >= 8.2
=> feat: tiflash use llvm17 to build on version >= 8.2

dockerfiles/ci/base/Dockerfile, dockerfiles/ci/release-build-base/Dockerfile
auto bump git version by renovate
=> chore: auto bump git version by renovate

.github/workflows/pull-cd-builder-images.yaml, .github/workflows/release-cd-builder-images.yaml
We can revert it after https://github.com/pingcap/tiflash/pull/9178 be merged.
=> ci: temp disable build for tiflash builder image

dockerfiles/bases/skaffold.yaml, dockerfiles/bases/tikv-base/fips.Dockerfile, dockerfiles/cd/builders/ng-monitoring/Dockerfile, dockerfiles/cd/builders/pd/Dockerfile, dockerfiles/cd/builders/tidb-dashboard/Dockerfile, dockerfiles/cd/builders/tidb/Dockerfile, dockerfiles/cd/builders/tiflash/Dockerfile, dockerfiles/cd/builders/tiflow/Dockerfile, dockerfiles/cd/builders/tikv/Dockerfile, dockerfiles/ci/base/Dockerfile, dockerfiles/ci/release-build-base/Dockerfile
___
Bug fix, Enhancement
___
- Updated CentOS 7 repository URLs across multiple Dockerfiles due to CentOS 7 reaching EOL.
- Removed `centos-release-scl` from package installations where applicable.
- Updated base image versions from `v1.8.0` to `v1.9.0` across multiple Dockerfiles.
- Added `unzip` package installation in `dockerfiles/cd/builders/tikv/Dockerfile`.
- Updated Go version to `1.21.12`, ORAS tool to `1.2.0`, and Git tool to `2.45.2` in `dockerfiles/ci/base/Dockerfile`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>3 files</summary><table>
<tr>
<td>
<details>
<summary><strong>skaffold.yaml</strong><dd><code>Update Skaffold template …
=> fix(dockerfiles): fix the eof problem of centos for ci cd builder images

dockerfiles/cd/builders/skaffold.yaml, dockerfiles/cd/builders/tidb-operator/Dockerfile
=> feat(dockerfiles/cd/builders): add builder image for tidb-operator

packages/delivery.yaml
coping master tag to DockerHub.
___
Enhancement
___
- Added a new image copy rule for `tidb-operator` to include the `master` tag.
- Introduced a new rule using `sync_trunk_community` for `tidb-operator`.
- Updated destination repositories for the `tidb-operator` image.
___
<tr>
<td>
<details>
<summary><strong>delivery.yaml</strong><dd><code>Add image copy rule for `tidb-operator` in delivery.yaml</code>&nbsp; </dd></summary>
<hr>
packages/delivery.yaml
<li>Added <code>master</code> tag to <code>tags_regex</code> for <code>tidb-operator</code> image copy rule.<br> <li> Introduced a new image copy rule for …
=> feat(packages): add image copy rule for tidb-operator

dockerfiles/cd/utils/release/Dockerfile
___
Bug fix, Enhancement
___
- Updated the Dockerfile to use a pre-built `gomplate` image from `hairyhenderson/gomplate:v4.1.0-alpine` instead of building it from source.
- Removed unnecessary steps and simplified the Dockerfile.
___
<tr>
<td>
<details>
<summary><strong>Dockerfile</strong><dd><code>Update `gomplate` installation to use pre-built image</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
dockerfiles/cd/utils/release/Dockerfile
<li>Removed custom build process for <code>gomplate</code>.<br> <li> Updated to use pre-built <code>gomplate</code> image from …
=> fix(deps): bump release utils images

dockerfiles/cd/utils/release/Dockerfile
Bug fix
___
- Fixed an issue in the Dockerfile where the required directory for `tiup` was not being created.
- Added a command to ensure the `~/.tiup/bin` directory is created during the Docker build process.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>Dockerfile</strong><dd><code>Create required directory for `tiup` in Dockerfile</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
dockerfiles/cd/utils/release/Dockerfile
<li>Added a command to create the required directory for <code>tiup</code>.<br> <li> Ensured the directory <code>~/.tiup/bin</code> is created during the Docker build <br>process.<br>
</details>
</td>
<td><a …
=> fix(dockerfiles/cd/utils/release): create required dir for tiup 

packages/packages.yaml.tmpl
- bump to oras v1.2.0
___
Enhancement
___
- Updated the Docker image tag for `ghcr.io/pingcap-qe/cd/utils/release` to `v20240325-60-gb6f8928` in `packages/packages.yaml.tmpl`.
- This update includes a bump to `oras` version `1.2.0`.
___
<tr>
<td>
<details>
<summary><strong>packages.yaml.tmpl</strong><dd><code>Update Docker image tag for release utilities</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
packages/packages.yaml.tmpl
<li>Updated the <code>image</code> tag for <code>ghcr.io/pingcap-qe/cd/utils/release</code> from …
=> chore(deps): update ghcr.io/pingcap-qe/cd/utils/release docker tag to v20240325-60-gb6f8928

packages/offline-packages.yaml.tmpl, packages/scripts/build-package-artifacts.sh.tmpl, packages/scripts/compose-offline-packages-artifacts.sh.tmpl
___
enhancement, bug fix
___
- Removed `profile` attribute from enterprise server package definitions in `packages/offline-packages.yaml.tmpl`.
- Added `-oy` flag to `yq` command for pretty output in `fetch_file_from_oci_artifact` function in `packages/scripts/build-package-artifacts.sh.tmpl`.
- Added `-oy` flag to `yq` command for pretty output in `fetch_file_from_oci_artifact` and `check_file_in_oci_artifact` functions in `packages/scripts/compose-offline-packages-artifacts.sh.tmpl`.
___
<tr>
<td>
<details>
<summary><strong>offline-packages.yaml.tmpl</strong><dd><code>Remove profile attribute from enterprise …
=> chore(dockerfiles/cd/utils/release): pretty output for offline package steps

dockerfiles/bases/pingcap-base/Dockerfile, dockerfiles/bases/skaffold.yaml, packages/packages.yaml.tmpl
=> fix(dockerfiles/bases): upgrade pkgs to fix security issues

packages/packages.yaml.tmpl
bump golang builders to fix security issues
the golang version all are v1.21.13.
=> fix(packges): update packages.yaml.tmpl

packages/offline-packages.yaml.tmpl, packages/packages.yaml.tmpl
=> chore(packages): remove arbiter from offline deployment packages

packages/offline-packages.yaml.tmpl, packages/packages.yaml.tmpl
Start v8.4.0:
- remove tidb-binlog artifacts and files.
- remove `binlogctl` in `ctl` tiup pkg.
- not build tidb-binlog from v8.4.0.
- remove `pump` and `drainer` tiup packages and other binaries from tidb-binlog into offline deloyment packages.
- bump etcdctl version to v3.5.15
=> feat(packages): update config for release version v8.4.0+

Justfile, dockerfiles/cd/builders/tiflash/Dockerfile
=> fix(dockerfiles/cd/builders/tiflash): upgrade openssl with conda pre-build package

.github/workflows/pull-cd-builder-images.yaml, .github/workflows/release-cd-builder-images.yaml, dockerfiles/cd/builders/skaffold.yaml
=> feat(dockerfiles/cd/builders): add go-1.23 and tiflash in to build workflows

packages/delivery.yaml
They are builded with new builder container.
=> build(packages): delivery experiment profile images

packages/packages.yaml.tmpl, packages/scripts/build-package-artifacts.sh.tmpl, packages/scripts/build-package-images.sh.tmpl, packages/scripts/compose-offline-packages-artifacts.sh.tmpl
- support zip type url, oci artifacts, or local file.
- update etcd url for ctl pkg in range [v8.4.0, )
=> feat(packages): update tiup ctl package config for range [v8.4.0, )

packages/packages.yaml.tmpl
=> fix(packages): bump tiup-ctl version to v1.16.0 for `ctl` package

.github/workflows/pull-cd-builder-images.yaml, .github/workflows/pull-verify-packages-config.yaml, .github/workflows/release-cd-builder-images.yaml, dockerfiles/cd/builders/skaffold.yaml, packages/README.md
=> fix(dockerfiles//cd/builders): bump golang version to v1.23.1

dockerfiles/bases/ng-monitoring-base/Dockerfile, dockerfiles/bases/ng-monitoring-base/release-6.5.Dockerfile, dockerfiles/bases/pd-base/Dockerfile, dockerfiles/bases/pd-base/release-6.5.Dockerfile, dockerfiles/bases/pingcap-base/Dockerfile, dockerfiles/bases/skaffold.yaml, dockerfiles/bases/tidb-base/Dockerfile, dockerfiles/bases/tidb-base/release-6.5.Dockerfile, dockerfiles/bases/tiflash-base/Dockerfile, dockerfiles/bases/tikv-base/Dockerfile, dockerfiles/bases/tikv-base/fips.Dockerfile, dockerfiles/bases/tikv-base/release-6.5.Dockerfile, dockerfiles/bases/tools-base/Dockerfile, dockerfiles/bases/tools-base/release-6.5.Dockerfile
add clean step to rmove `/var/cache/yum`.
=> fix(dockerfiles/bases): shrink base image size

packages/packages.yaml.tmpl
=> fix(pingcap/tidb-operator): fix builder for new release

dockerfiles/ci/base/Dockerfile
=> fix(dockerfiles/ci/base): fix open-jdk installation

packages/scripts/build-package-artifacts.sh.tmpl, packages/scripts/compose-offline-packages-artifacts.sh.tmpl
From oras v1.2.0, there's a break change for cli option of sub command `discover`. Ref: https://github.com/oras-project/oras/releases/tag/v1.2.0
=> fix(packages/scripts): update to adjust new oras version

.github/scripts/ci.sh, packages/packages.yaml.tmpl
=> feat(packages): switch to new builder for `release` profile

dockerfiles/ci/jenkins/Dockerfile
=> fix(dockerfiles/ci/jenkins): set `USE_BAZEL_VERSION` env var to fixate the bazel version

dockerfiles/cd/builders/pd/Dockerfile, dockerfiles/cd/builders/tidb/Dockerfile
=> fix(dockerfiles/cd/builders): install findutils package in builder

.github/workflows/release-ci-runtime-images.yaml
support build image for ci/jenkins dockerfile
=> chore: support build image for ci/jenkins dockerfile

dockerfiles/ci/jenkins/tiflash/Dockerfile, dockerfiles/ci/jenkins/tikv/Dockerfile
add tools wget&hostname&free to tikv&tiflash ci images.
=> feat: add tools wget&hostname&free to tikv&tiflash ci images

dockerfiles/ci/base/Dockerfile, dockerfiles/ci/jenkins/Dockerfile
Add more tools in ci jenkins image
* mysql client
* python package: s3cmd, requests
* gocoverage
=> feat(ci/jenkins): add more tools to  ci jenkins image

dockerfiles/ci/base/Dockerfile
Install mysql client from mariadb v5.5.68.
=> feat: add tools mariadb client 5.5.68

packages/packages.yaml.tmpl
With the new version of tiflash builder to improve the performance of the artifacts.
Ref: https://github.com/pingcap/tiflash/pull/9587
=> fix(pingcap/tiflash): fix builder image

dockerfiles/cd/builders/tiflash/Dockerfile, dockerfiles/cd/builders/tiflash/centos7/Dockerfile, packages/packages.yaml.tmpl
Ref https://github.com/pingcap/tiflash/pull/9587, it changes the build script paths.
=> chore(tiflash): update build steps for tiflash starts v8.5.0

dockerfiles/cd/builders/tiflash/Dockerfile, dockerfiles/cd/builders/tiflash/centos7/Dockerfile
=> feat(dockerfiles/cd/builders/tiflash): update image docker file for new tiflash builder

dockerfiles/cd/builders/ng-monitoring/centos7/Dockerfile, dockerfiles/cd/builders/pd/centos7/Dockerfile, dockerfiles/cd/utils/release/Dockerfile, dockerfiles/ci/release-build-base/Dockerfile, packages/packages.yaml.tmpl
=> chore(deps): bump golang version from 1.23.2 to 1.23.3

packages/packages.yaml.tmpl
=> fix(packages): compatible with centos7 devtoolset build toolchain

packages/scripts/get-delivery-target-images.ts
Use it to get the target images for delivery, we
can use it to check if the deliveries are ready.
Usage:
```bash
./packages/scripts/get-delivery-target-images.ts \
--config <url-or-filepath-of-delivery-yaml> \
--version <vX.Y.Z> \
--registry <the-source-registry-where-the-images-copied-from> \
--save_to <path-to-save-the-result-yaml>
```
=> feat(packages/scripts): add get-delivery-target-images.ts

packages/packages.yaml.tmpl
The `failpoint` target will only be used in testing env, I agreed with the testing team: agreed to remove the race option.
=> fix(tidb,pd): remove race flag for failpoint target

packages/packages.yaml.tmpl
The new tag image is built with `dwz` tool installed.
=> build(tikv): bump tikv build image tag

.github/scripts/ci.sh, packages/delivery.yaml, packages/packages.yaml.tmpl
Artifacts:
- tiup package `cdc` nightly version will be published to tiup mirror from this repo(switched from tiflow repo).
- container image `pingcap/ticdc:master` in docker hub will be published from this repo.
=> feat(pingcap/ticdc): support publish artifacts for the repo's trunk branch

dockerfiles/products/ticdc/Dockerfile, packages/packages.yaml.tmpl
This pull request includes changes to the Dockerfile for the `ticdc` product and updates to the `packages.yaml.tmpl` file to modify the build and publish process for CDC components. The most important changes are:
Dockerfile changes:
* Added a new base image argument and updated the Dockerfile to use this base image for building the `ticdc` product.
Build and publish process updates:
* Updated the version constraint and added new steps to build and publish CDC components from the `pingcap/ticdc` repository for versions starting from `v9.0.0`.
* Added detailed steps for installing the Node.js toolchain and building `dm-master`, `dm-worker`, `dmctl`, and `dm-syncer` components.
* Defined new artifact configurations for `dm-master`, `dm-worker`, `dmctl`, and container images for `dm` and …
=> feat(pingcap/ticdc): we build and publish cdc components from `pingcap/ticdc` repo since v9.0.0

packages/packages.yaml.tmpl
since v9.0.0, cdc will be produced from `pingcap/ticdc` github repo.
=> fix(pingcap/ctl): add cdc binary from `pingcap/ticdc/package` repo

dockerfiles/cd/utils/release/Dockerfile
add curl tool into release util image
=> chore(dockerfiles/cd/utils/release): add curl tool in the release util image

.github/scripts/ci.sh, dockerfiles/products/tiflow/sync-diff-inspector.Dockerfile, packages/README.md, packages/delivery.yaml, packages/offline-packages.yaml.tmpl, packages/packages.yaml.tmpl
- migrate building from `pingcap/tidb-tools` to `pingcap/tiflow` repo.
- publish tiup package: `sync-diff-inspector`.
- build and deliver image to `docker.io/pingcap/sync-diff-inspector`.
- compose offline toolkit package with tiup package `sync-diff-inspector` rather than `sync_diff_inspector` raw binary file.
Close #546
=> refactor(pingcap/tiflow,pingcap/tidb-tools): refactor the building of sync-diff-inspector tool

packages/packages.yaml.tmpl
This pull request includes changes to the `packages/packages.yaml.tmpl` file to add a new profile option for the build steps.
Changes to build profiles:
* [`packages/packages.yaml.tmpl`](diffhunk://#diff-31ae6e632fba4bcb68649d473c355898c698ab9cf7946e4fc2189e6fbdf33fc7L1762-R1762): Added `failpoint` to the `profile` list for versions `~8.4.0-0` and `>= 6.1.0-0, < 8.4.0-0`. [[1]](diffhunk://#diff-31ae6e632fba4bcb68649d473c355898c698ab9cf7946e4fc2189e6fbdf33fc7L1762-R1762) [[2]](diffhunk://#diff-31ae6e632fba4bcb68649d473c355898c698ab9cf7946e4fc2189e6fbdf33fc7L1810-R1810)
=> fix(tiflash): fix failpoint profile for history release branches

packages/packages.yaml.tmpl
This pull request includes a new container image definition in the `packages/packages.yaml.tmpl` file. The change adds a new image for the `backup-manager` component, specifying its type, artifactory repository, context, Dockerfile, and target build stage.
Changes in `components`:
* Added a new container image definition for `backup-manager` with details on its type, artifactory repository, context, Dockerfile, and target build stage.
=> Configure backup-manager image for operator-v2

packages/packages.yaml.tmpl
This pull request includes a change to the `packages/packages.yaml.tmpl` file to update the repository name for the `backup-manager` container image. The change ensures that the repository name is consistent with other images in the project.
Repository name update:
* [`packages/packages.yaml.tmpl`](diffhunk://#diff-31ae6e632fba4bcb68649d473c355898c698ab9cf7946e4fc2189e6fbdf33fc7L1475-R1475): Changed the repository name for the `backup-manager` container image from `backup-manager` to `tidb-backup-manager`.
=> fix(tidb-operator): fix repo of `tidb-backup-manager`

packages/offline-packages.yaml.tmpl
for v8.5.x and lower versions, we still release with the latest code from master branch.
=> revert(packages): revert the changes on offline packages about sync_diff_inspector tool for history versions

packages/packages.yaml.tmpl
This pull request includes changes to the `packages/packages.yaml.tmpl` file to update the version constraints and add new build steps for the `tiflash` component.
* Updated the version range for `tiflash` from `[v6.1.0, v8.4.0)` to `[v6.2.0, v8.4.0)` to reflect the new minimum supported version.
* Added a new version range `[v6.1.0, v6.2.0)` with specific build steps for both `release` and `enterprise` profiles. These steps include scripts for building on Darwin and Linux, utilizing `ccache` for improved build performance, and moving build outputs to a constant path.
=> fix(packages): remove failpoint targets for tiflash v6.1 version series

packages/delivery.yaml
sync new ticdc image since v9.0.0-beta
=> fix: sync new ticdc image since v9.0.0-beta

packages/delivery.yaml
sync new ticdc image from pingcap/ticdc repo since v9.0.0-beta in ga.
=> fix: sync new ticdc image since v9.0.0-beta in ga

dockerfiles/cd/builders/tikv/centos7/Dockerfile
This pull request includes a minor update to the `dockerfiles/cd/builders/tikv/centos7/Dockerfile` to enhance the build environment by adding additional Perl modules.
Enhancements to build environment:
* [`dockerfiles/cd/builders/tikv/centos7/Dockerfile`](diffhunk://#diff-bceb5c0ebca4756e35995a954151c6bbf2b8f74ff379c76fb99be4d26ad87875L23-R23): Added `perl-IPC-Cmd` and `perl-Data-Dumper` to the list of packages installed to ensure necessary Perl modules are available.
=> feat(dockerfiles/cd/builders/tikv): add perl cpans in centos7 builder

packages/packages.yaml.tmpl
This pull request updates the Rust builder image used in the `packages.yaml.tmpl` file and removes an unnecessary installation step for the `protobuf-compiler` tool. These changes improve the build process by aligning with updated dependencies and simplifying the build script.
* Updated the Rust builder image from `docker.io/library/rust:1.85.0` to `ghcr.io/pingcap-qe/cd/builders/tikv:v2024.10.8-139-g74d1fec-centos7-devtoolset10`, ensuring compatibility with the latest build tools and dependencies.
* Removed the installation step for the `protobuf-compiler` tool (`apt-get update && apt-get install -y protobuf-compiler`), as it is no longer required in the build process.
=> feat(packages): update TiCI builder to use PingCAP's pre-configured image

dockerfiles/products/tikv/next-gen.Dockerfile, packages/packages.yaml.tmpl
Historical debt introduced before 2021 Year: not updated and synchronized in time, but this has no impact on production/operation. 
Tip: 'expose' in `Dockerfile` is just a description.
**Do NOT add `EXPOSE 20180`** because:
- The container's entrypoint is set to `/tikv-server`
- `cse-ctl` won't be running automatically
- Including an `EXPOSE` for a port that won't be listening could be misleading for other developers
=> chore(dockerfiles): fix expose port for tikv-ctl

packages/packages.yaml.tmpl
> Close PingCAP-QE/ci#3543
This pull request updates the `packages/packages.yaml.tmpl` file to introduce support for next-generation builds starting from version `v9.0.0-0`. It also refines the build and artifact generation process for different profiles, such as `release`, `next-gen`, `enterprise`, and `failpoint`, and adjusts the version ranges for build configurations.
* **Next-gen build support**: Added support for next-generation builds starting from version `v9.0.0-0`. This includes specific build steps for profiles like `release`, `next-gen`, `enterprise`, and `failpoint`.
* **Artifact definitions**: Defined detailed artifact generation rules for various profiles, including file paths, descriptions, and TiUP publishing configurations for tools like `pd-server`, `pd-recover`, and …
=> feat(packages): add next-gen build and artifacts for PD v9.0.0 and above

dockerfiles/products/tiflash/Dockerfile
Enable profiling capability but incative default.
Ref pingcap/tiflash#9320
=> feature(dockerfiles): set MALLOC_CONF environment variable in TiFlash image

.github/workflows/pull-ci-runtime-images.yaml, .github/workflows/release-ci-runtime-images.yaml, dockerfiles/ci/skaffold.yaml
Introduced a new job to detect file changes in the CI and release workflows, allowing conditional execution of subsequent jobs based on the presence of changes in specific Dockerfiles and configuration files. Updated the skaffold configuration to reflect the new job structure and renamed the CI module to `ci-tici` for clarity.
- Added `detect-changes` job to both workflows.
- Updated job dependencies to conditionally run based on detected changes.
- Refactored skaffold configuration to include `ci-tici`.
=> feat(workflows/ci): add change detection jobs for CI and release workflows

packages/delivery.yaml
We have migrated repositories from `qa/*` to `pingcap/*` and `tikv/*` for about 1 year.
It's time to remove the sync rules.
=> fix(packages): Remove QA registry destinations from image_copy_rules

.github/workflows/release-ci-runtime-images.yaml
The default runner build will encounter an error.
```shell
System.IO.IOException: No space left on device : '/home/runner/actions-runner/cached/_diag/Worker_20250704-084430-utc.log'
```
=> chore(workflow): Update CI workflow to use arc-runner-set-pingcap-qe for image publishing

packages/delivery.yaml
Fix unexpected inconsistency of image name
=> rename prestop-hook to prestop-checker

packages/packages.yaml.tmpl
Build it with new builder image with llvm-clang 17+.
=> fix(tici): update builder image for tici and remove devtoolset source step

packages/delivery.yaml
This pull request updates the `image_copy_rules` in the `packages/delivery.yaml` file to include additional destination repositories for various components. These changes ensure that images are also delivered to the `gcr.io/pingcap-public/dbaas` repository for each specified component.
* Added `gcr.io/pingcap-public/dbaas` as a destination repository for the following components:
- `ticdc`
- `tidb`
- `br`
- `tidb-lightning`
- `dm`
- `tiflash`
- `tikv`
- `pd`
=> feat(packages): delivery images built on trunk branches to gcr.io

packages/delivery.yaml
This pull request updates the image delivery configuration in `packages/delivery.yaml` to better distinguish between community and enterprise edition images for several products. The main changes involve adding explicit rules and descriptions for syncing enterprise edition images, ensuring they are delivered to the appropriate repositories, and clarifying the handling of community edition images.
**Image sync rules and configuration:**
* Added a detailed description and tag pattern for the `sync_trunk_enterprise` definition to clearly specify its purpose for enterprise edition images.
* Modified the `image_copy_rules` to deliver enterprise edition images (`sync_trunk_enterprise`) for `tidb`, `br`, and `tidb-lightning` to `gcr.io/pingcap-public/dbaas`, and community edition images to …
=> fix(packages): deliver trunk branch enterprise images to GCR.io for `pingcap/tidb` repo

dockerfiles/cd/builders/tiflash/centos7/Dockerfile, packages/packages.yaml.tmpl
This pull request adds a new `tiup` component to the `packages.yaml.tmpl` configuration, enabling support for building, packaging, and distributing TiUP and its related binaries. The changes provide metadata, build instructions, artifact definitions, and descriptions for several TiUP subcomponents.
**Addition of TiUP packaging and distribution:**
* Introduced a new `tiup` section under `components:` in `packages/packages.yaml.tmpl`, including metadata such as repo URL, git reference, SHA, versioning, and artifactory settings for package distribution.
* Defined build instructions and builder images for TiUP, specifying the use of the `tici` builder image for Linux platforms and supported architectures.
**Artifact and subcomponent definitions:**
* Added artifact definitions for TiUP and its …
=> feat(packages): add tiup component packaging and artifact definitions

dockerfiles/bases/pingcap-base/Dockerfile, dockerfiles/bases/skaffold.yaml
- Create user and group in `pingcap-base` image.
- Update skaffold tag template to v1.10.0.
=> feat(dockerfiles/bases): add pingcap user and group to base Dockerfile

dockerfiles/bases/skaffold.yaml, dockerfiles/bases/tikv-base/fips.Dockerfile
=> chore(dockerfiles/bases/tikv-base): bump base image and tag to v1.10.0

packages/scripts/build-package-images.sh.tmpl
- Introduce -M option to specify multi-arch result file path
- Update help text and argument parsing for new option
- Pass result file to collect_and_push_multi_arch_images
- Record multi-arch images in specified YAML file using yq
=> feat(packages/scripts): add support for multi-arch result file in build script

packages/scripts/build-package-images.sh.tmpl
- Remove separate multi-arch result file logic
- Consolidate all image tag results into PUSH_RESULT_SAVE_FILE
- Update yq commands to write multi-arch tags to unified result file
- Simplify argument parsing and help output
=> refactor(packages/scripts): refactor image result file handling and multi-arch tagging

packages/scripts/build-package-images.sh.tmpl
The URL field was duplicating information already present in the repo and tag fields, making the output cleaner and less redundant.
=> refactor(packages/scripts): update build script to remove redundant image URL field

dockerfiles/bases/debugging/Dockerfile, dockerfiles/bases/debugging/structure-test/test.yaml, dockerfiles/bases/skaffold.yaml
This pull request introduces a new debugging base image to the Docker build system, complete with a wide array of system inspection, debugging, and observability tools. It also adds a comprehensive container structure test suite to verify the presence and functionality of these tools. The Skaffold configuration is updated to build this new image for multiple architectures.
**Debugging Base Image and Tooling:**
* Added a new `debugging` Docker image (`dockerfiles/bases/debugging/Dockerfile`) that installs a broad set of system inspection, debugging, tracing, and observability tools (e.g., `htop`, `iotop`, `perf`, `gdb`, `bpftrace`, `fio`, `tcpdump`, `jq`, `tmux`, `ripgrep`, and more). Also includes the addition of Brendan Gregg's `iosnoop` perf tool.
**Testing and Verification:**
* …
=> feat(dockerfiles/bases): add debugging base Dockerfile and structure tests skeleton
